name: miel_work_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.8.17+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  flutter_launcher_icons: ^0.14.3
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  http: ^1.3.0
  flutter_spinkit: ^5.2.1
  page_transition: ^2.2.1
  modal_bottom_sheet: ^3.0.0
  alert_banner: ^1.0.1
  syncfusion_localizations: ^28.2.9
  syncfusion_flutter_pdfviewer: ^28.2.9
  file_picker: ^9.0.2
  file_selector: ^1.0.3
  pdf: ^3.11.3
  universal_html: ^2.2.4
  common_utils: ^2.1.0
  month_picker_dialog: ^6.0.3
  multiple_stream_builder: ^3.0.2
  scroll_to_index: ^3.0.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  flutter_datetime_picker_plus: ^2.2.0
  flutter_app_badge: ^2.0.2
  currency_text_input_formatter: ^2.2.9
  flutter_file_dialog: ^3.0.2
  flutter_colorpicker: ^1.1.0
  calendar_date_picker2: ^1.1.9
  package_info_plus: ^8.3.0
  version: ^3.0.2
  in_app_review: ^2.0.10
  custom_pop_up_menu: ^1.2.4
  signature: ^5.5.0
  calendar_view: ^1.4.0
  flutter_image_compress: ^2.4.0

  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1

dependency_overrides:
  flutter_colorpicker:
    git:
      url: https://github.com/mchome/flutter_colorpicker
      ref: master  # or 786d04363f587b818ce585d25b9c2bb62de95aba
  url_launcher_ios: ^6.3.2
  flutter_app_badger:
    git:
      url: https://github.com/g123k/flutter_app_badger.git
      ref: 33cbee6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SourceHanSansJP-Bold
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Bold.otf
    - family: SourceHanSansJP-Regular
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Regular.otf

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/icon.png'
  adaptive_icon_background: '#FFD54F'
  adaptive_icon_foreground: 'assets/images/icon_adaptive_foreground.png'